name: Pull Request CI

on:

  pull_request:

jobs:
  pullrequest:
    env:
      COMPOSE_DOCKER_CLI_BUILD: 0
      COMPOSE_INTERACTIVE_NO_CLI: 1  ## fixes the input device is not a TTY on docker compose
      DOCKER_BUILDKIT: 0
      DOCKERGPR_USER: ${{ github.actor }}
      DOCKERGPR_PASS: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:

      - uses: actions/checkout@v2

      # https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: |
          pip install --upgrade --upgrade-strategy eager -r requirements.txt -r requirements-dev.txt

      - name: Execute lint, tests, coverage
        run: tox -e coverage,py3

