name: Pull Request CI

on:

  pull_request:

jobs:
  pullrequest:
    env:
      COMPOSE_DOCKER_CLI_BUILD: 0
      COMPOSE_INTERACTIVE_NO_CLI: 1  ## fixes the input device is not a TTY on docker compose
      DOCKER_BUILDKIT: 0
      DOCKERGPR_USER: ${{ github.actor }}
      DOCKERGPR_PASS: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:

      - uses: actions/checkout@v2

      - name: Log into Github Package Registry
        run: echo "$DOCKERGPR_PASS" | docker login docker.pkg.github.com -u $DOCKERGPR_USER --password-stdin

      - name: Build test image and run tests with GPR cache
        run: make test-image-gpr

