name: Tag CI

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  push:
    env:
      COMPOSE_DOCKER_CLI_BUILD: 0
      COMPOSE_INTERACTIVE_NO_CLI: 1  ## fixes the input device is not a TTY on docker compose
      DOCKER_BUILDKIT: 0
      DOCKERGPR_USER: ${{ github.actor }}
      DOCKERGPR_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USER: ${{ github.actor }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          # Remove refs/tags
          TAG=$(echo "${{ github.ref }} | sed -e 's,.*/\(.*\),\1,'")
          # Get vX.Y
          TAG_VER=$(echo $TAG | sed -e 's,\.[0-9]\+$,,')
          IMAGE="sdelrio/hs110-exporter"
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=version_image::${IMAGE}:${TAG_VER}
          echo ::set-output name=latest_image::${IMAGE}:latest
          echo ::set-output name=tag::${TAG}

      - name: Build test image and run tests
        run: make test-image-gpr

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log into registry
        run: echo "$DOCKERHUB_PASS" | docker login -u $DOCKERHUB_USER --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: Dockerfile
          # Set the desired build target here
          target: run
          push: true
          tags: ${{ steps.prep.outputs.tagged_image }},${{ steps.prep.outputs.latest_image }},${{ steps.prep.outputs.version_image }}
          cache-from: type=local,src=/tmp/.buildx-cache
          # Note the mode=max here
          # More: https://github.com/moby/buildkit#--export-cache-options
          # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Trigger new Operation-Resource actions for Deployment
        run: |
          commitMsg=$(git log --format=%B -n 1 ${{ github.event.after }} --pretty=oneline --abbrev-commit)
          branchName="master"
          echo "TAG=${{ steps.prep.outputs.tagged_image }}"
          echo "commitMsg: $commitMsg"
          echo "branchName: $branchName"
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.OPERATION_RESOURCE_REPOSITORY_ACCESS_TOKEN }}" \
          https://api.github.com/repos/sdelrio/gitops-hs110/dispatches \
          --data \
          '
          {
            "event_type": "product",
            "client_payload": {
              "action": "distribute",
              "commitmsg": "'"$commitMsg"'",
              "dirName": "hs110-exporter",
              "newTag": "'"${{ steps.prep.outputs.tagged_image }}"'",
              "baseRef":"'"$branchName"'"
            }
          }'


